retrieval:
  is_train: true
  data:
    path_data: data/UITSquad/train.json
    path_evaluator: data/UITSquad/dev.json
    mode_chunking: True
    max_length: 256
    overlapping_size: 80
    method_generation: bm25
    method_train: triplet
    n_negative: 10
  model:
    model_name_or_path: khanhbk20/vn-sentence-embedding
    model_save_path: Model
    batch_size: 32
    epochs: 4

reader:
  is_train: false