retrieval:
  is_train: true
  data:
    path_data: data/UITSquad/train.json
    path_evaluator: data/UITSquad/dev.json
    mode_chunking: false
    max_length: 300
    overlapping_size: 60
    method_generation: sbert
    method_train: triplet
    sbert_model_gen: keepitreal/vietnamese-sbert
    n_negative: 8
  model:
    model_name_or_path: keepitreal/vietnamese-sbert
    model_save_path: Model
    batch_size: 32
    epochs: 5

reader:
  is_train: false