data:
  path_train: data/hand/data2.json
  path_evaluator: data/hand/edu_test.json

config_data:
  max_length_document: 300
  mode_chunking: false
  overlapping_size: 80

retrieval:
  is_train: false
  parameters:
    method_generation: random
    method_train: triplet
    n_negative: 4
  model:
    model_name_or_path: khanhbk20/vn-sentence-embedding
    model_save_path: model/retrieval
    batch_size: 32
    epochs: 4
    loss_fn_config:
      name: MultipleNegativesRankingLoss

reader:
  is_train: true
  model:
    model_name_or_path: khanhbk20/mrc_large
    num_train_epochs: 10
    learning_rate: 5e-5
    batch_size_training: 8
    batch_size_eval: 8
    gradient_accumulation_steps: 1
    save_strategy: epoch
    logging_strategy: steps
    metric_for_best_model: f1
    logging_step: 1
    max_length: 368
    output_dir: model/qa/large