retrieval:
  is_train: true
  data:
    path_data: data/UITSquad/train.json
    path_evaluator: data/UITSquad/dev.json

  parameters:
    mode_chunking: True
    max_length: 256
    overlapping_size: 80
    method_generation: bm25
    method_train: triplet
    n_negative: 10
  model:
    model_name_or_path: khanhbk20/vn-sentence-embedding
    model_save_path: Model
    batch_size: 32
    epochs: 4

reader:
  is_train: true
  data:
    path_train: data/UITSquad/train.json
    path_evaluator: data/UITSquad/dev.json

  parameters:
    mode_chunking: True
    max_length: 350
    overlapping_size: 80
    is_valid: True

  model:
    model_name_or_path: khanhbk20/mrc_testing
    num_train_epochs: 70
    learning_rate: 1e-4
    batch_size_training: 16
    batch_size_eval: 32
    gradient_accumulation_steps: 1
    save_strategy: epoch
    metric_for_best_model: f1
