retrieval:
  is_train: true
  data:
    path_data: data/UITSquad/train.json
    path_evaluator: data/UITSquad/dev.json
    mode_chunking: True
    max_length: 250
    overlapping_size: 100
    method_generation: random
    method_train: triplet
    n_negative: 6
  model:
    model_name_or_path: khanhbk20/vn-sentence-embedding
    model_save_path: Model
    batch_size: 32
    epochs: 5

reader:
  is_train: false