from e2eqavn.mrc import *
from e2eqavn.processor import QATextProcessor
qa_process = QATextProcessor()
question = "Cơ sở giáo dục phương Tây đầu tiên có thể được gọi là gì"
context1 = ". Cơ sở giáo dục phương Tây đầu tiên có thể được gọi là viện đại học là một trường y khoa nổi tiếng thành lập ở Salerno, Ý, vào thế kỷ thứ 9.  Trường này thu hút sinh viên từ khắp châu Âu.  Tuy nhiên, nó vẫn chỉ là một trường y khoa.  Viện đại học thực sự đầu tiên là Viện Đại học Bologna thành lập ở Bologna, Ý, cuối thế kỷ 11.  Nó trở thành một cơ sở giáo dục được nhiều người kính trọng, nhất là trong lĩnh vực luật tôn giáo và luật dân sự.  Viện đại học đầu tiên ra đời ở Bắc Âu là Viện Đại học Paris, thành lập trong khoảng 1150 đến 1170.  Viện đại học này nổi tiếng về giảng dạy thần học, và nó trở thành hình mẫu cho các viện đại học khác ở Bắc Âu, chẳng hạn như Viện Đại học Oxford ở Anh thành lập vào cuối thế kỷ 12.  Các viện đại học Paris và Oxford bao gồm các trường đại học vốn là nơi ở dành cho các học giả. . Những viện đại học ban đầu này là những đoàn thể sinh viên và giảng viên, được các giáo hoàng, hoàng đế, và nhà vua ban quyền.  Viện Đại học Napoli, do Hoàng đế Frederick II thành lập vào năm 1224 ở Ý, là cơ sở đầu tiên được thành lập dưới thẩm quyền của một hoàng đế, trong khi Viện Đại học Toulouse, do Giáo hoàng Grêgôriô IX lập ra vào năm 1229 ở Pháp, là cơ sở đầu tiên được thành lập qua một sắc lệnh của giáo hoàng.  Những viện đại học này được quyền tự trị, miễn là họ không dạy vô thần và dị giáo.  Sinh viên và giảng viên cùng nhau tự bầu ra viện trưởng.  Tuy nhiên, như cái giá phải trả cho sự độc lập, họ phải tự lo kinh phí.  Do đó mà các giảng viên phải thu học phí, và để đảm bảo cuộc sống, họ phải làm hài lòng sinh viên"

context1 = " ".join(qa_process.string_tokenize(qa_process.strip_context(context1))).strip()

question = " ".join(qa_process.string_tokenize(question)).strip()
mrc_reader = MRCReader.from_pretrained('khanhbk20/mrc_testing')
print(mrc_reader.qa_inference(question=question, documents=[context1]))