wandb_version: 1

mode_chunking:
  desc: null
  value: true
max_length:
  desc: null
  value: 400
overlapping_size:
  desc: null
  value: 80
is_valid:
  desc: null
  value: true
model_name_or_path:
  desc: null
  value: khanhbk20/mrc_testing
num_train_epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 5e-5
batch_size_training:
  desc: null
  value: 16
batch_size_eval:
  desc: null
  value: 32
gradient_accumulation_steps:
  desc: null
  value: 1
save_strategy:
  desc: null
  value: epoch
logging_strategy:
  desc: null
  value: steps
metric_for_best_model:
  desc: null
  value: f1
logging_step:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1683643611.129627
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 75
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 75
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.15.2
      6: 4.28.1
      8:
      - 2
      - 5
